server:
  port: 1010

spring:
  application:
    name: AUTH-SERVICE

  zipkin:
    base-url: http://localhost:9411/

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oauth
    username: shorasul
    password: 1232

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update